### PR TITLE
Foundry generator: Add command line flag for specifying the system version

### PR DESCRIPTION
**Pull request by tech-ticks**

### CODE REVIEW

**Comment by Willowlark** [comment]
Is this something we can include a default on? Keeps cmd line calls simpler if you aren't specifically focused on something involving that parameter

**Comment by tech-ticks** [comment]
Although it would be more convenient, the problem with a default value here is that this field should always be accurate. The system will probably use it in the future to determine whether data needs to be migrated to a new version. If we use a hardcoded default like `0.1.0`, it might trigger false positives. So the default version would have to be increased after every Foundry system release, which would require updates to this repo even when no data has changed.

**Comment by Willowlark** [comment]
Right, but if a casual user wants to say, rebuild the foundry data with health bars on, or with a different set of images, they also have to hunt down the current foundry version. I have no problem bumping the default as foundry updates, I'll even do that to master directly, but this way everything you need to run foundry.py is in this repo.

**Comment by tech-ticks** [comment]
Alright, let's keep the version in sync then. I've updated the branch to make the argument optional.

**Pull request merged**
